### PR TITLE
compose support

### PR DESCRIPTION
**Pull request by KarthickCk**
- compose interoperability with xml

### CODE REVIEW

**Comment by Daniel-Contextual** [comment]
Hi @KarthickCk . I was looking at your code and I noticed that `loadComposeView()` is never invoked. 
Screenshot 2024-02-14 at 2 31 16 pm

Please see my screenshot. I can't see Hello World at all.

**Comment by KarthickCk** [comment]
> Hi @KarthickCk . I was looking at your code and I noticed that `loadComposeView()` is never invoked. Screenshot 2024-02-14 at 2 31 16 pm
> 
> Please see my screenshot. I can't see Hello World at all.

**Comment by KarthickCk** [comment]
> > Hi @KarthickCk . I was looking at your code and I noticed that `loadComposeView()` is never invoked. Screenshot 2024-02-14 at 2 31 16 pm
> > Please see my screenshot. I can't see Hello World at all.

enabled hello world! pls verify

**Pull request merged**
